# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 560)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.task_label = QtWidgets.QLabel(Dialog)
        self.task_label.setGeometry(QtCore.QRect(70, 245, 160, 40))
        self.task_label.setStyleSheet("background-color: transparent;\n"
"font-family: Helvetica;\n"
"font-size: 20px;\n"
"font: bold;\n"
"color: rgb(0,0,0);\n"
"\n"
"")
        self.task_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.task_label.setObjectName("task_label")
        self.deadline_label = QtWidgets.QLabel(Dialog)
        self.deadline_label.setGeometry(QtCore.QRect(70, 140, 160, 40))
        self.deadline_label.setStyleSheet("background-color: transparent;\n"
"font-family: Helvetica;\n"
"font-size: 20px;\n"
"font: bold;\n"
"color: rgb(0,0,0);\n"
"\n"
"")
        self.deadline_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.deadline_label.setObjectName("deadline_label")
        self.task_name_label = QtWidgets.QLabel(Dialog)
        self.task_name_label.setGeometry(QtCore.QRect(70, 35, 160, 40))
        self.task_name_label.setStyleSheet("background-color: transparent;\n"
"font-family: Helvetica;\n"
"font-size: 20px;\n"
"font: bold;\n"
"color: rgb(0,0,0);\n"
"\n"
"")
        self.task_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.task_name_label.setObjectName("task_name_label")
        self.user_input_task_name = QtWidgets.QLineEdit(Dialog)
        self.user_input_task_name.setGeometry(QtCore.QRect(70, 70, 280, 50))
        self.user_input_task_name.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"font-family: Helvetica;\n"
"font-size: 18px;\n"
"border: 3px solid;\n"
"border-color: rgb(222, 222, 222);\n"
"font: bold;\n"
"color: rgb(0,0,0);\n"
"padding-left: 10px;")
        self.user_input_task_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_input_task_name.setObjectName("user_input_task_name")
        self.user_input_task = QtWidgets.QTextEdit(Dialog)
        self.user_input_task.setGeometry(QtCore.QRect(70, 280, 280, 150))
        self.user_input_task.setAcceptDrops(False)
        self.user_input_task.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"font-family: Helvetica;\n"
"font-size: 18px;\n"
"border: 3px solid;\n"
"border-color: rgb(222, 222, 222);\n"
"color: rgb(0,0,0);\n"
"padding-left: 10px;")
        self.user_input_task.setObjectName("user_input_task")
        self.user_input_datetime = QtWidgets.QDateTimeEdit(Dialog)
        self.user_input_datetime.setGeometry(QtCore.QRect(70, 175, 280, 50))
        self.user_input_datetime.setStyleSheet("background-color: rgb(246, 246, 246);\n"
"font-family: Helvetica;\n"
"font-size: 18px;\n"
"border: 3px solid;\n"
"border-color: rgb(222, 222, 222);\n"
"color: rgb(0,0,0);\n"
"padding-left: 10px;")
        self.user_input_datetime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_input_datetime.setObjectName("user_input_datetime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 470, 281, 58))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"   background-color: rgb(93, 217, 110);\n"
"   font-family: Helvetica;\n"
"   font-size: 18px;\n"
"   border: 3px solid; \n"
"   border-color: rgb(66, 135, 76);\n"
"   font: bold;\n"
"   color: rgb(0,0,0);\n"
"   width: 80px;\n"
"   height: 50px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background-color: rgb(242, 155, 155);\n"
"   font-family: Helvetica;\n"
"   font-size: 18px;\n"
"   border: 3px solid; \n"
"   border-color: rgb(130, 57, 57);\n"
"   font: bold;\n"
"   color: rgb(0,0,0);\n"
"   width: 80px;\n"
"   height: 50px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.task_label.setText(_translate("Dialog", "Enter the task"))
        self.deadline_label.setText(_translate("Dialog", "Deadline"))
        self.task_name_label.setText(_translate("Dialog", "Task name"))
        self.user_input_task_name.setText(_translate("Dialog", "Проверить на точность"))
#         self.user_input_task.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'Helvetica\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "SEND"))
        self.pushButton_3.setText(_translate("Dialog", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
